# Generated by Django 2.2.7 on 2019-12-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0002_auto_20191201_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(blank=True, max_length=100, verbose_name='고양이'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만든날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lnt_lng',
            field=models.CharField(max_length=100, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최근수정날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, choices=[('h', 'horo'), ('l', 'lolens'), ('s', 'spicyhoro')], max_length=100, verbose_name='유저이'),
        ),
    ]
