# Generated by Django 2.2.7 on 2019-12-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0003_auto_20191201_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, choices=[('h', 'horo'), ('l', 'lolens'), ('s', 'spicyhoro')], max_length=100, verbose_name='유저이름'),
        ),
    ]
